In [2]:
import pandas as pd

data_folder = '../data/'

In [3]:
stations = pd.read_csv(data_folder + 'stations/treated_data/2021.11.08_Endereços-BikeSAMPA.csv')
stations

,id,name,address,lat,lon,VAGAS/DOCK AGORA,DATA INAUGURAÇÃO
0,1,Largo da Batata,"Av. Brigadeiro Faria Lima, esquina R. Teodoro ...",-23.566831,-46.693741,83,2018-01-30
1,2,SESC Pinheiros,"R. Ferreira de Araújo, em frente ao número 1031",-23.566920,-46.698190,15,2020-12-19
2,3,CPTM Pinheiros,"R. Gilberto Sabino, 138/ ao lado do ponto de ô...",-23.566478,-46.701258,15,2018-01-30
3,4,Rua Diogo Moreira,"Av. Brigadeiro Faria Lima, na altura do número...",-23.569145,-46.692003,23,2018-05-10
4,5,Chicão Vive,"Rua Butantã , 192",-23.569894,-46.697897,7,2019-12-03
...,...,...,...,...,...,...,...
254,347,Metrô Brooklin,"Av. Santo Amaro, próximo ao acesso do metrô Br...",-23.626894,-46.687573,29,2018-12-12
255,354,Praça Oswaldo Cruz,"Praça Oswaldo Cruz, oposto 97",-23.571604,-46.644266,11,2019-12-21
256,355,R. Dr. Rafael de Barros,"Rua Dr. Rafael de Barros, em frente ao 253 / P...",-23.572712,-46.646530,19,2019-01-31
257,358,Shopping Villa Lobos,"Avenida das Nações Unidas, 4777",-23.551665,-46.722563,7,2018-12-12
258,359,CENU,"Av das Nações Unidas, 12901/ Próximo à esquina...",-23.609980,-46.696412,11,2018-12-05

In [6]:
stations_coord = stations[['id', 'lat', 'lon']]
stations_coord

      id        lat        lon
0      1 -23.566831 -46.693741
1      2 -23.566920 -46.698190
2      3 -23.566478 -46.701258
3      4 -23.569145 -46.692003
4      5 -23.569894 -46.697897
..   ...        ...        ...
254  347 -23.626894 -46.687573
255  354 -23.571604 -46.644266
256  355 -23.572712 -46.646530
257  358 -23.551665 -46.722563
258  359 -23.609980 -46.696412

[259 rows x 3 columns]

In [5]:
year = '2022'
trips = pd.read_csv(data_folder + 'trips/loaded_trips/trips_' + year + '.csv')
trips

,date,tripduration,start_station_name_old,start_station_id,starttime,end_station_name_old,end_station_id,stoptime,birth_year,age,per_day,hour,week_day,weekend,holiday,start_station_name,end_station_name,distance
0,2021-11-01,13825,346 - Bacaetava,346.0,2021-11-01 08:09:23,345 - R. Henrique Fischer,345.0,2021-11-01 11:59:48,1986-01-01 00:00:00,35.0,2021-11-01,8,0,False,False,Bacaetava,R. Henrique Fischer,0.448
1,2021-11-01,989,22 - Rua Leopoldo Couto,22.0,2021-11-01 19:34:03,335 - R. Ribeiro do Vale,335.0,2021-11-01 19:50:32,1990-01-01 00:00:00,31.0,2021-11-01,19,0,False,False,Rua Leopoldo Couto,R. Ribeiro do Vale,3.325
2,2021-11-01,10426,5 - Chicão Vive,5.0,2021-11-01 13:30:33,220 - R. dos Pinheiros,220.0,2021-11-01 16:24:19,1995-01-01 00:00:00,26.0,2021-11-01,13,0,False,False,Chicão Vive,R. dos Pinheiros,2.618
3,2021-11-01,451,1 - Largo da Batata,1.0,2021-11-01 08:48:46,236 - Praça Ernâni Braga,236.0,2021-11-01 08:56:17,1972-01-01 00:00:00,49.0,2021-11-01,8,0,False,False,Largo da Batata,Praça Ernâni Braga,1.698
4,2021-11-01,9726,23 - CPTM Vila Olímpia,23.0,2021-11-01 10:10:29,143 - Rua João Cachoeira,143.0,2021-11-01 12:52:35,1963-01-01 00:00:00,58.0,2021-11-01,10,0,False,False,CPTM Vila Olímpia,Rua João Cachoeira,2.300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927436,2022-04-30,723,250 - Bandejão Química,250.0,2022-04-30 13:39:48,249 - Bandejão Central,249.0,2022-04-30 13:51:51,1997-01-01 00:00:00,25.0,2022-04-30,13,5,True,False,Bandejão Química,Bandejão Central,1.736
927437,2022-04-30,4894,197 - Albuquerque Lins,197.0,2022-04-30 20:47:15,282 - Cunha Horta,282.0,2022-04-30 22:08:49,1988-01-01 00:00:00,34.0,2022-04-30,20,5,True,False,Albuquerque Lins,Cunha Horta,2.281
927438,2022-04-30,13320,1 - Largo da Batata,1.0,2022-04-30 12:05:28,14 - Museu da Casa Brasileira,14.0,2022-04-30 15:47:28,1956-01-01 00:00:00,66.0,2022-04-30,12,5,True,False,Largo da Batata,Museu da Casa Brasileira,1.848
927439,2022-04-30,550,208 - Alameda Lorena,208.0,2022-04-30 18:00:24,72 - Queluz,72.0,2022-04-30 18:09:34,1983-01-01 00:00:00,39.0,2022-04-30,18,5,True,False,Alameda Lorena,Queluz,2.797
927440,2022-04-30,1272,36 - E.E. Aristides de Castro,36.0,2022-04-30 14:28:31,21 - Parque do Povo portão 1,21.0,2022-04-30 14:49:43,1967-01-01 00:00:00,55.0,2022-04-30,14,5,True,False,E.E. Aristides de Castro,Parque do Povo portão 1,1.440

In [9]:
merge = trips.merge(stations_coord, how = 'left', left_on=['start_station_id'],
                    right_on=['id'])

merge = merge.drop(['id'], axis = 1)

merge = merge.rename(columns={'lat': 'lat_start',
                              'lon': 'lon_start'})

merge = merge.merge(stations_coord, how = 'left', left_on=['end_station_id'],
                    right_on=['id'])

merge = merge.drop(['id'], axis = 1)

merge = merge.rename(columns={'lat': 'lat_end',
                              'lon': 'lon_end'})

merge

,date,tripduration,start_station_name_old,start_station_id,starttime,end_station_name_old,end_station_id,stoptime,birth_year,age,...,week_day,weekend,holiday,start_station_name,end_station_name,distance,lat_start,lon_start,lat_end,lon_end
0,2021-11-01,13825,346 - Bacaetava,346.0,2021-11-01 08:09:23,345 - R. Henrique Fischer,345.0,2021-11-01 11:59:48,1986-01-01 00:00:00,35.0,...,0,False,False,Bacaetava,R. Henrique Fischer,0.448,-23.621392,-46.694738,-23.619406,-46.696564
1,2021-11-01,989,22 - Rua Leopoldo Couto,22.0,2021-11-01 19:34:03,335 - R. Ribeiro do Vale,335.0,2021-11-01 19:50:32,1990-01-01 00:00:00,31.0,...,0,False,False,Rua Leopoldo Couto,R. Ribeiro do Vale,3.325,-23.589205,-46.683923,-23.610685,-46.685913
2,2021-11-01,10426,5 - Chicão Vive,5.0,2021-11-01 13:30:33,220 - R. dos Pinheiros,220.0,2021-11-01 16:24:19,1995-01-01 00:00:00,26.0,...,0,False,False,Chicão Vive,R. dos Pinheiros,2.618,-23.569894,-46.697897,-23.564337,-46.679855
3,2021-11-01,451,1 - Largo da Batata,1.0,2021-11-01 08:48:46,236 - Praça Ernâni Braga,236.0,2021-11-01 08:56:17,1972-01-01 00:00:00,49.0,...,0,False,False,Largo da Batata,Praça Ernâni Braga,1.698,-23.566831,-46.693741,-23.556796,-46.702026
4,2021-11-01,9726,23 - CPTM Vila Olímpia,23.0,2021-11-01 10:10:29,143 - Rua João Cachoeira,143.0,2021-11-01 12:52:35,1963-01-01 00:00:00,58.0,...,0,False,False,CPTM Vila Olímpia,Rua João Cachoeira,2.300,-23.593918,-46.691268,-23.584108,-46.677960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927436,2022-04-30,723,250 - Bandejão Química,250.0,2022-04-30 13:39:48,249 - Bandejão Central,249.0,2022-04-30 13:51:51,1997-01-01 00:00:00,25.0,...,5,True,False,Bandejão Química,Bandejão Central,1.736,-23.565099,-46.724342,-23.560721,-46.721660
927437,2022-04-30,4894,197 - Albuquerque Lins,197.0,2022-04-30 20:47:15,282 - Cunha Horta,282.0,2022-04-30 22:08:49,1988-01-01 00:00:00,34.0,...,5,True,False,Albuquerque Lins,Cunha Horta,2.281,-23.539000,-46.657904,-23.544779,-46.648967
927438,2022-04-30,13320,1 - Largo da Batata,1.0,2022-04-30 12:05:28,14 - Museu da Casa Brasileira,14.0,2022-04-30 15:47:28,1956-01-01 00:00:00,66.0,...,5,True,False,Largo da Batata,Museu da Casa Brasileira,1.848,-23.566831,-46.693741,-23.580880,-46.684709
927439,2022-04-30,550,208 - Alameda Lorena,208.0,2022-04-30 18:00:24,72 - Queluz,72.0,2022-04-30 18:09:34,1983-01-01 00:00:00,39.0,...,5,True,False,Alameda Lorena,Queluz,2.797,-23.559920,-46.670266,-23.572734,-46.658604
927440,2022-04-30,1272,36 - E.E. Aristides de Castro,36.0,2022-04-30 14:28:31,21 - Parque do Povo portão 1,21.0,2022-04-30 14:49:43,1967-01-01 00:00:00,55.0,...,5,True,False,E.E. Aristides de Castro,Parque do Povo portão 1,1.440,-23.586793,-46.676082,-23.589044,-46.688218