In [2]:
import pandas as pd

stations_distances = pd.read_csv('../data/stations/distance/stations_distance.csv')

stations_distances

       id_x  id_y  distance
0         1     1     0.000
1         1     2     1.268
2         1     3     1.158
3         1     4     0.358
4         1     5     1.631
...     ...   ...       ...
67076   359   347     2.969
67077   359   354     8.524
67078   359   355     8.098
67079   359   358     8.766
67080   359   359     0.000

[67081 rows x 3 columns]

In [3]:
year = '2020'
trips = pd.read_csv("../data/trips/loaded_trips/trips_" +year+ ".csv")
trips

,Unnamed: 0,date,Index,tripduration,start_station_name_old,index_start,starttime,end_station_name_old,index_end,stoptime,...,birth_year,initial_station_latitude,initial_station_longitude,final_station_latitude,final_station_longitude,age,start_station_name,end_station_name,id_y,distance
0,0,2020-01-01,4758319,3596,76 - 8° Batalhão,76.0,2020-01-01 16:14:43,91 - Paulista 778,91.0,2020-01-01 17:14:39,...,1996-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,24.0,8º Batalhão,Paulista 778,91.0,1.833
1,1,2020-01-01,4758337,2922,21 - Parque do Povo portão 1,21.0,2020-01-01 16:18:08,21 - Parque do Povo portão 1,21.0,2020-01-01 17:06:50,...,NaN,NaN,NaN,NaN,NaN,NaN,Parque do Povo portão 1,Parque do Povo portão 1,21.0,0.000
2,2,2020-01-01,4758338,199,304 - Gandavo,304.0,2020-01-01 16:18:10,304 - Gandavo,304.0,2020-01-01 16:21:29,...,1997-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,23.0,Gandavo,Gandavo,304.0,0.000
3,3,2020-01-01,4758339,4151,131 - Pq. Ibirapuera Portão 06,131.0,2020-01-01 16:18:19,43 - Auditório Ibirapuera,43.0,2020-01-01 17:27:30,...,1984-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,36.0,Ibirapuera Portão 06,Herois da FEB,43.0,13.051
4,4,2020-01-01,4758340,6065,198 - Marechal Deodoro,198.0,2020-01-01 16:18:25,196 - Alameda Barros,196.0,2020-01-01 17:59:30,...,1998-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,22.0,Marechal Deodoro,Alameda Barros,196.0,0.359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2354964,2354964,2020-12-31,4478491,2817,96 - Tutóia,96.0,2020-12-31 16:19:00,74 - Círculo Militar,74.0,2020-12-31 17:05:57,...,1987-01-01,-23.573823,-46.651414,-23.580154,-46.656249,33.0,Tutóia,Círculo Militar,74.0,1.281
2354965,2354965,2020-12-31,4478371,5870,146 - Ibirapuera portão 03,146.0,2020-12-31 10:58:34,146 - Ibirapuera portão 03,146.0,2020-12-31 12:36:24,...,1987-01-01,-23.589043,-46.652787,-23.589043,-46.652787,33.0,Ibirapuera Portão 03,Ibirapuera Portão 03,146.0,0.000
2354966,2354966,2020-12-31,4479320,10486,347 - Metrô Brooklin,347.0,2020-12-31 11:41:36,25 - Rua Helena,25.0,2020-12-31 14:36:22,...,1978-01-01,-23.626894,-46.687573,-23.593063,-46.685352,42.0,Metrô Brooklin,Rua Helena,25.0,5.255
2354967,2354967,2020-12-31,4478800,349,224 - Metrô Fradique Coutinho,224.0,2020-12-31 11:40:46,224 - Metrô Fradique Coutinho,224.0,2020-12-31 11:46:35,...,1998-01-01,-23.565532,-46.684883,-23.565532,-46.684883,22.0,Metrô Fradique Coutinho,Metrô Fradique Coutinho,224.0,0.000
2354968,2354968,2020-12-31,4478240,3025,33 - Ibirapuera Portão 08,33.0,2020-12-31 10:35:05,31 - Rua Jacques Félix,31.0,2020-12-31 11:25:30,...,1996-01-01,-23.588029,-46.665460,-23.591632,-46.671364,24.0,Ibirapuera Portão 08,NaN,NaN,NaN

In [4]:
trips = trips.drop(['id_y'], axis = 1)

In [5]:
merge = trips.drop(['Unnamed: 0'], axis = 1)

In [6]:
merge

,date,Index,tripduration,start_station_name_old,index_start,starttime,end_station_name_old,index_end,stoptime,per_day,...,trip_id,birth_year,initial_station_latitude,initial_station_longitude,final_station_latitude,final_station_longitude,age,start_station_name,end_station_name,distance
0,2020-01-01,4758319,3596,76 - 8° Batalhão,76.0,2020-01-01 16:14:43,91 - Paulista 778,91.0,2020-01-01 17:14:39,2020-01-01,...,5885062BikeSampa,1996-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,24.0,8º Batalhão,Paulista 778,1.833
1,2020-01-01,4758337,2922,21 - Parque do Povo portão 1,21.0,2020-01-01 16:18:08,21 - Parque do Povo portão 1,21.0,2020-01-01 17:06:50,2020-01-01,...,5885083BikeSampa,NaN,NaN,NaN,NaN,NaN,NaN,Parque do Povo portão 1,Parque do Povo portão 1,0.000
2,2020-01-01,4758338,199,304 - Gandavo,304.0,2020-01-01 16:18:10,304 - Gandavo,304.0,2020-01-01 16:21:29,2020-01-01,...,5885111BikeSampa,1997-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,23.0,Gandavo,Gandavo,0.000
3,2020-01-01,4758339,4151,131 - Pq. Ibirapuera Portão 06,131.0,2020-01-01 16:18:19,43 - Auditório Ibirapuera,43.0,2020-01-01 17:27:30,2020-01-01,...,5885086BikeSampa,1984-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,36.0,Ibirapuera Portão 06,Herois da FEB,13.051
4,2020-01-01,4758340,6065,198 - Marechal Deodoro,198.0,2020-01-01 16:18:25,196 - Alameda Barros,196.0,2020-01-01 17:59:30,2020-01-01,...,5885091BikeSampa,1998-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,22.0,Marechal Deodoro,Alameda Barros,0.359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2354964,2020-12-31,4478491,2817,96 - Tutóia,96.0,2020-12-31 16:19:00,74 - Círculo Militar,74.0,2020-12-31 17:05:57,2020-12-31,...,9077382BikeSampa,1987-01-01,-23.573823,-46.651414,-23.580154,-46.656249,33.0,Tutóia,Círculo Militar,1.281
2354965,2020-12-31,4478371,5870,146 - Ibirapuera portão 03,146.0,2020-12-31 10:58:34,146 - Ibirapuera portão 03,146.0,2020-12-31 12:36:24,2020-12-31,...,9075846BikeSampa,1987-01-01,-23.589043,-46.652787,-23.589043,-46.652787,33.0,Ibirapuera Portão 03,Ibirapuera Portão 03,0.000
2354966,2020-12-31,4479320,10486,347 - Metrô Brooklin,347.0,2020-12-31 11:41:36,25 - Rua Helena,25.0,2020-12-31 14:36:22,2020-12-31,...,9076109BikeSampa,1978-01-01,-23.626894,-46.687573,-23.593063,-46.685352,42.0,Metrô Brooklin,Rua Helena,5.255
2354967,2020-12-31,4478800,349,224 - Metrô Fradique Coutinho,224.0,2020-12-31 11:40:46,224 - Metrô Fradique Coutinho,224.0,2020-12-31 11:46:35,2020-12-31,...,9076102BikeSampa,1998-01-01,-23.565532,-46.684883,-23.565532,-46.684883,22.0,Metrô Fradique Coutinho,Metrô Fradique Coutinho,0.000
2354968,2020-12-31,4478240,3025,33 - Ibirapuera Portão 08,33.0,2020-12-31 10:35:05,31 - Rua Jacques Félix,31.0,2020-12-31 11:25:30,2020-12-31,...,9075731BikeSampa,1996-01-01,-23.588029,-46.665460,-23.591632,-46.671364,24.0,Ibirapuera Portão 08,NaN,NaN

In [7]:
len(merge.columns)

24

In [14]:
trips = trips.drop(['initial_station_latitude', 'initial_station_longitude',
                    'final_station_latitude', 'final_station_longitude'], axis = 1)

In [7]:
merge = trips.merge(stations_distances, how = 'left', left_on=['index_start', 'index_end'],
                    right_on=['id_x', 'id_y'])

merge = merge.drop(['id_x', 'id_y'], axis = 1)
merge

,date,Index,tripduration,start_station_name_old,index_start,starttime,end_station_name_old,index_end,stoptime,per_day,...,birth_year,initial_station_latitude,initial_station_longitude,final_station_latitude,final_station_longitude,age,start_station_name,end_station_name,id_y,distance
0,2020-01-01,4758319,3596,76 - 8° Batalhão,76.0,2020-01-01 16:14:43,91 - Paulista 778,91.0,2020-01-01 17:14:39,2020-01-01,...,1996-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,24.0,8º Batalhão,Paulista 778,91.0,1.833
1,2020-01-01,4758337,2922,21 - Parque do Povo portão 1,21.0,2020-01-01 16:18:08,21 - Parque do Povo portão 1,21.0,2020-01-01 17:06:50,2020-01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,Parque do Povo portão 1,Parque do Povo portão 1,21.0,0.000
2,2020-01-01,4758338,199,304 - Gandavo,304.0,2020-01-01 16:18:10,304 - Gandavo,304.0,2020-01-01 16:21:29,2020-01-01,...,1997-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,23.0,Gandavo,Gandavo,304.0,0.000
3,2020-01-01,4758339,4151,131 - Pq. Ibirapuera Portão 06,131.0,2020-01-01 16:18:19,43 - Auditório Ibirapuera,43.0,2020-01-01 17:27:30,2020-01-01,...,1984-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,36.0,Ibirapuera Portão 06,Herois da FEB,43.0,13.051
4,2020-01-01,4758340,6065,198 - Marechal Deodoro,198.0,2020-01-01 16:18:25,196 - Alameda Barros,196.0,2020-01-01 17:59:30,2020-01-01,...,1998-01-01 00:00:00.000000000,NaN,NaN,NaN,NaN,22.0,Marechal Deodoro,Alameda Barros,196.0,0.359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2354964,2020-12-31,4478491,2817,96 - Tutóia,96.0,2020-12-31 16:19:00,74 - Círculo Militar,74.0,2020-12-31 17:05:57,2020-12-31,...,1987-01-01,-23.573823,-46.651414,-23.580154,-46.656249,33.0,Tutóia,Círculo Militar,74.0,1.281
2354965,2020-12-31,4478371,5870,146 - Ibirapuera portão 03,146.0,2020-12-31 10:58:34,146 - Ibirapuera portão 03,146.0,2020-12-31 12:36:24,2020-12-31,...,1987-01-01,-23.589043,-46.652787,-23.589043,-46.652787,33.0,Ibirapuera Portão 03,Ibirapuera Portão 03,146.0,0.000
2354966,2020-12-31,4479320,10486,347 - Metrô Brooklin,347.0,2020-12-31 11:41:36,25 - Rua Helena,25.0,2020-12-31 14:36:22,2020-12-31,...,1978-01-01,-23.626894,-46.687573,-23.593063,-46.685352,42.0,Metrô Brooklin,Rua Helena,25.0,5.255
2354967,2020-12-31,4478800,349,224 - Metrô Fradique Coutinho,224.0,2020-12-31 11:40:46,224 - Metrô Fradique Coutinho,224.0,2020-12-31 11:46:35,2020-12-31,...,1998-01-01,-23.565532,-46.684883,-23.565532,-46.684883,22.0,Metrô Fradique Coutinho,Metrô Fradique Coutinho,224.0,0.000
2354968,2020-12-31,4478240,3025,33 - Ibirapuera Portão 08,33.0,2020-12-31 10:35:05,31 - Rua Jacques Félix,31.0,2020-12-31 11:25:30,2020-12-31,...,1996-01-01,-23.588029,-46.665460,-23.591632,-46.671364,24.0,Ibirapuera Portão 08,NaN,NaN,NaN

In [8]:
merge.to_csv("../data/trips/loaded_trips/trips_" +year+ ".csv", index=False)